### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by MPC7500** [kpl-addons/plugin.video.odysee#1]
Hello, is it compatible with 19.3? I can't install it as a zip.

**Comment by karlo2105** [comment]
I confirm, it doesn't install on Kodi 19.4 either due to dependences issues.

**Comment by rysson** [comment]
It's a falstart. There is no code, only empty git repo for new plugin.
You have to find odysee somewhere else.
Sorry broo

**Comment by heppix** [comment]
Just a quick note. There is something more in the repo. If you want, you can check it again :)
